{
 "title": "network health",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(zcash_net_in_bytes_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "bytes - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "repeat": "job",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zcash_net_in_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes read [1s]"
    },
    {
     "expr": "sum(rate(zcash_net_out_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes written [1s]"
    }
   ]
  },
  {
   "title": "bytes - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zcash_net_in_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes read [1s]"
    },
    {
     "expr": "sum(rate(zcash_net_out_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes written [1s]"
    }
   ]
  },
  {
   "title": "bytes - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zcash_net_in_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes read [1s]"
    },
    {
     "expr": "sum(rate(zcash_net_out_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes written [1s]"
    }
   ]
  },
  {
   "title": "bytes - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zcash_net_in_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes read [1s]"
    },
    {
     "expr": "sum(rate(zcash_net_out_bytes_total{job=\"$job\"}[1s]))",
     "legendFormat": "bytes written [1s]"
    }
   ]
  },
  {
   "title": "peer readiness - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zcash_net_peers{job=\"$job\"}",
     "legendFormat": "total peers"
    },
    {
     "expr": "pool_num_ready{job=\"$job\"}",
     "legendFormat": "ready peers"
    },
    {
     "expr": "pool_num_unready{job=\"$job\"}",
     "legendFormat": "unready peers"
    }
   ]
  },
  {
   "title": "peer readiness - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zcash_net_peers{job=\"$job\"}",
     "legendFormat": "total peers"
    },
    {
     "expr": "pool_num_ready{job=\"$job\"}",
     "legendFormat": "ready peers"
    },
    {
     "expr": "pool_num_unready{job=\"$job\"}",
     "legendFormat": "unready peers"
    }
   ]
  },
  {
   "title": "peer readiness - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zcash_net_peers{job=\"$job\"}",
     "legendFormat": "total peers"
    },
    {
     "expr": "pool_num_ready{job=\"$job\"}",
     "legendFormat": "ready peers"
    },
    {
     "expr": "pool_num_unready{job=\"$job\"}",
     "legendFormat": "unready peers"
    }
   ]
  },
  {
   "title": "peer readiness - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zcash_net_peers{job=\"$job\"}",
     "legendFormat": "total peers"
    },
    {
     "expr": "pool_num_ready{job=\"$job\"}",
     "legendFormat": "ready peers"
    },
    {
     "expr": "pool_num_unready{job=\"$job\"}",
     "legendFormat": "unready peers"
    }
   ]
  },
  {
   "title": "candidate set - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "candidate_set_disconnected{job=\"$job\"}",
     "legendFormat": "recently stopped peers"
    },
    {
     "expr": "candidate_set_failed{job=\"$job\"}",
     "legendFormat": "failed candidates"
    },
    {
     "expr": "candidate_set_gossiped{job=\"$job\"}",
     "legendFormat": "never attempted candidates"
    },
    {
     "expr": "candidate_set_pending{job=\"$job\"}",
     "legendFormat": "connection attempt pending"
    },
    {
     "expr": "candidate_set_responded{job=\"$job\"}",
     "legendFormat": "recent peers"
    },
    {
     "expr": "candidate_set_recently_live{job=\"$job\"}",
     "legendFormat": "recently live peers"
    }
   ]
  },
  {
   "title": "candidate set - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "candidate_set_disconnected{job=\"$job\"}",
     "legendFormat": "recently stopped peers"
    },
    {
     "expr": "candidate_set_failed{job=\"$job\"}",
     "legendFormat": "failed candidates"
    },
    {
     "expr": "candidate_set_gossiped{job=\"$job\"}",
     "legendFormat": "never attempted candidates"
    },
    {
     "expr": "candidate_set_pending{job=\"$job\"}",
     "legendFormat": "connection attempt pending"
    },
    {
     "expr": "candidate_set_responded{job=\"$job\"}",
     "legendFormat": "recent peers"
    },
    {
     "expr": "candidate_set_recently_live{job=\"$job\"}",
     "legendFormat": "recently live peers"
    }
   ]
  },
  {
   "title": "candidate set - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "candidate_set_disconnected{job=\"$job\"}",
     "legendFormat": "recently stopped peers"
    },
    {
     "expr": "candidate_set_failed{job=\"$job\"}",
     "legendFormat": "failed candidates"
    },
    {
     "expr": "candidate_set_gossiped{job=\"$job\"}",
     "legendFormat": "never attempted candidates"
    },
    {
     "expr": "candidate_set_pending{job=\"$job\"}",
     "legendFormat": "connection attempt pending"
    },
    {
     "expr": "candidate_set_responded{job=\"$job\"}",
     "legendFormat": "recent peers"
    },
    {
     "expr": "candidate_set_recently_live{job=\"$job\"}",
     "legendFormat": "recently live peers"
    }
   ]
  },
  {
   "title": "candidate set - $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "candidate_set_disconnected{job=\"$job\"}",
     "legendFormat": "recently stopped peers"
    },
    {
     "expr": "candidate_set_failed{job=\"$job\"}",
     "legendFormat": "failed candidates"
    },
    {
     "expr": "candidate_set_gossiped{job=\"$job\"}",
     "legendFormat": "never attempted candidates"
    },
    {
     "expr": "candidate_set_pending{job=\"$job\"}",
     "legendFormat": "connection attempt pending"
    },
    {
     "expr": "candidate_set_responded{job=\"$job\"}",
     "legendFormat": "recent peers"
    },
    {
     "expr": "candidate_set_recently_live{job=\"$job\"}",
     "legendFormat": "recently live peers"
    }
   ]
  },
  {
   "title": "connection state - $job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(command) (zebra_net_connection_state{job=\"$job\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "connection state - $job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(command) (zebra_net_connection_state{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "connection state - $job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(command) (zebra_net_connection_state{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "connection state - $job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(command) (zebra_net_connection_state{job=\"$job\"})"
    }
   ]
  }
 ]
}